### ISSUE TITLE
Gazebo 9.0.0 crashes when loading the urdf from master

### ISSUE THREAD

**Issue by micko-plz** [Halodi/halodi-robot-models#8]
`ros2 launch halodi-controller-gazebo halodi-controller-gazebo.launch.py`
^^Gazebo server segfaults on when trying to launch using the latest files on the master branch.

Unfortunately it doesn't return an error message.

The problem is with the .obj files for the qb_hands.

There is no error if we edit eve_r3.urdf so that the meshes used for the hands are from the original .stl descriptions.

Maybe the obj files for the hands are just wrong, I've no idea how they were generated.

**Comment by jespersmith** [comment]
This issue is fixed in Gazebo 9.15, however it does complain about missing materials
